version: "3.9"

services:

  api:
    build: .
    container_name: ecommerce_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - APP_NAME=E-Commerce API
      - DATABASE_URL=postgresql://ecommerce_user:ecommerce_pass@db:5432/ecommerce_db
      - SECRET_KEY=supersecretkey123456789abcdefghijklmnopqrstuvwxyz
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - REDIS_URL=redis://redis:6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000"

  db:
    image: postgres:15-alpine
    container_name: ecommerce_db
    environment:
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecommerce_pass
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecommerce_user -d ecommerce_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: ecommerce_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: ecommerce_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: ecommerce_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=db:5432
      - GF_DATABASE_NAME=ecommerce_db
      - GF_DATABASE_USER=ecommerce_user
      - GF_DATABASE_PASSWORD=ecommerce_pass
    depends_on:
      - db
      - prometheus
    restart: unless-stopped

volumes:
  postgres_data: